spring.application.name=demo_repository_r2dbc
## Logging configuration
logging.level.org.springframework.transaction=trace
logging.level.Exposed=trace
logging.level.org.demo.repository=debug
# Spring Docs
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/docs.json
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/docs
